//! `LuaExposable` — trait used by the `#[lua_methods]` proc-macro to
//! list device-specific methods that should be reachable from the
//! daemon's Lua REPL. Defining the trait here (in cirrus-core, no mlua
//! dependency) lets device authors annotate their `impl` blocks
//! without pulling mlua into every device crate.
//!
//! The actual mlua-side wiring lives in cirrus-cli; it walks the
//! `lua_methods()` slice and bolts each entry onto a Lua table that
//! shadows the standard `LuaDevice` userdata.
//!
//! ## Generated shape
//!
//! Given:
//!
//! ```ignore
//! #[cirrus_derive::lua_methods]
//! impl Diffractometer {
//!     #[lua_method]
//!     pub async fn set_orientation(&self, h: f64, k: f64, l: f64)
//!         -> Result<(), CirrusError> { /* ... */ }
//! }
//! ```
//!
//! The macro emits (next to the original `impl`):
//!
//! ```ignore
//! impl ::cirrus_core::lua_exposable::LuaExposable for Diffractometer {
//!     fn lua_methods() -> &'static [::cirrus_core::lua_exposable::LuaMethodEntry] {
//!         &[
//!             LuaMethodEntry {
//!                 name: "set_orientation",
//!                 arity: 3,
//!                 dispatch: |this, args| { /* downcast + parse + call + serialize */ },
//!             },
//!         ]
//!     }
//! }
//! ```
//!
//! The `dispatch` fn signature uses serde_json values to keep mlua
//! out of cirrus-core. The cirrus-cli adapter converts mlua values
//! into json on the way in and out.

use std::any::Any;

/// One LuaExposable method entry. Generated by `#[lua_methods]`.
#[derive(Copy, Clone)]
pub struct LuaMethodEntry {
    /// Lua-visible method name (matches the Rust fn name unless
    /// overridden via `#[lua_method(name = "...")]` — not yet
    /// supported, but the field is here for forward compat).
    pub name: &'static str,
    /// Number of args the method takes (excluding `self`). Used for
    /// arity-checking on the Lua side before invocation.
    pub arity: usize,
    /// Dispatcher: downcasts `this` to the concrete type, parses
    /// args from `serde_json::Value`s, calls the method, and
    /// serializes the return.
    ///
    /// A `Result::Err` here surfaces as a Lua error from the user's
    /// perspective; a successful `Result::Ok(Value::Null)` becomes
    /// `nil` in Lua.
    pub dispatch: fn(
        this: &(dyn Any + Send + Sync),
        args: &[serde_json::Value],
    ) -> Result<serde_json::Value, String>,
}

/// Implemented by types that opt in to `#[lua_methods]`.
pub trait LuaExposable: Send + Sync + 'static {
    /// Static slice of methods this type exposes to Lua.
    fn lua_methods() -> &'static [LuaMethodEntry];
}
