//! Plan + device registry. The set of plans + devices `bsrs-qs` can run.

use crate::core::lua_exposable::LuaMethodEntry;
use crate::core::msg::{
    CollectableObj, FlyableObj, LocatableObj, MovableObj, ReadableObj, StageableObj, TriggerableObj,
};
use crate::core::plan::Plan;
use serde_json::Value;
use std::any::Any;
use std::collections::HashMap;
use std::sync::Arc;

/// One device's `#[lua_methods]` table + a downcast handle.
#[derive(Clone)]
pub struct LuaExposedEntry {
    /// Static method table generated by the proc macro.
    pub methods: &'static [LuaMethodEntry],
    /// `Arc<dyn Any + Send + Sync>` cast of the concrete device, so
    /// the dispatch fns (which take `&dyn Any`) can downcast.
    pub device: Arc<dyn Any + Send + Sync>,
}

/// Plan factory function. Builds a `Plan` from JSON arguments
/// (`{"args": [...], "kwargs": {...}}`).
pub type PlanFactory =
    Arc<dyn Fn(&Registry, &Value) -> Result<Plan, String> + Send + Sync + 'static>;

/// Parameter kind, mirroring Python's `inspect.Parameter.kind` so the
/// `plans_allowed` / `plans_existing` wire dict matches bluesky-queueserver's
/// `_process_plan` output (`kind: {name, value}`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ParamKind {
    /// `0` — positional only.
    PositionalOnly,
    /// `1` — positional or keyword (the common case).
    PositionalOrKeyword,
    /// `2` — `*args`.
    VarPositional,
    /// `3` — keyword only (after a bare `*`).
    KeywordOnly,
    /// `4` — `**kwargs`.
    VarKeyword,
}

impl ParamKind {
    fn wire_name(self) -> &'static str {
        match self {
            ParamKind::PositionalOnly => "POSITIONAL_ONLY",
            ParamKind::PositionalOrKeyword => "POSITIONAL_OR_KEYWORD",
            ParamKind::VarPositional => "VAR_POSITIONAL",
            ParamKind::KeywordOnly => "KEYWORD_ONLY",
            ParamKind::VarKeyword => "VAR_KEYWORD",
        }
    }
    fn wire_value(self) -> u8 {
        match self {
            ParamKind::PositionalOnly => 0,
            ParamKind::PositionalOrKeyword => 1,
            ParamKind::VarPositional => 2,
            ParamKind::KeywordOnly => 3,
            ParamKind::VarKeyword => 4,
        }
    }
}

/// One plan parameter's schema — the subset of bluesky-queueserver's
/// `_process_plan` parameter dict that bsrs populates. Rendered to
/// `{name, description?, kind:{name,value}, annotation?:{type}, default?}`.
#[derive(Clone, Debug)]
pub struct ParamSpec {
    /// Parameter name (REQUIRED on the wire).
    pub name: String,
    /// Human description (from the plan docstring's parameter section).
    pub description: Option<String>,
    /// Positional/keyword kind.
    pub kind: ParamKind,
    /// Type string rendered into `annotation: {type: <this>}`.
    pub annotation_type: Option<String>,
    /// String representation of the default value; `None` = required.
    pub default: Option<String>,
}

impl ParamSpec {
    /// A required, untyped parameter of the given kind.
    pub fn new(name: impl Into<String>, kind: ParamKind) -> Self {
        Self {
            name: name.into(),
            description: None,
            kind,
            annotation_type: None,
            default: None,
        }
    }
    /// Attach a human description.
    pub fn with_description(mut self, d: impl Into<String>) -> Self {
        self.description = Some(d.into());
        self
    }
    /// Attach a type annotation string.
    pub fn with_type(mut self, t: impl Into<String>) -> Self {
        self.annotation_type = Some(t.into());
        self
    }
    /// Attach a default value (string representation); marks it optional.
    pub fn with_default(mut self, d: impl Into<String>) -> Self {
        self.default = Some(d.into());
        self
    }

    fn to_json(&self) -> Value {
        let mut m = serde_json::Map::new();
        m.insert("name".into(), Value::String(self.name.clone()));
        if let Some(d) = &self.description {
            m.insert("description".into(), Value::String(d.clone()));
        }
        m.insert(
            "kind".into(),
            serde_json::json!({ "name": self.kind.wire_name(), "value": self.kind.wire_value() }),
        );
        if let Some(t) = &self.annotation_type {
            m.insert("annotation".into(), serde_json::json!({ "type": t }));
        }
        if let Some(d) = &self.default {
            m.insert("default".into(), Value::String(d.clone()));
        }
        Value::Object(m)
    }
}

/// A registered plan's schema — bluesky-queueserver's `_process_plan` dict,
/// restricted to the fields bsrs can supply. Empty by default: a plan
/// registered without metadata renders `description: ""`, `parameters: []`
/// (the pre-metadata behavior).
#[derive(Clone, Debug, Default)]
pub struct PlanMeta {
    /// Multi-line plan description (docstring summary).
    pub description: Option<String>,
    /// Ordered parameter schema.
    pub parameters: Vec<ParamSpec>,
}

impl PlanMeta {
    fn to_json(&self, name: &str) -> Value {
        serde_json::json!({
            "name": name,
            "module": "bsrs_qs",
            "description": self.description.clone().unwrap_or_default(),
            "properties": { "is_generator": true },
            "parameters": self.parameters.iter().map(ParamSpec::to_json).collect::<Vec<_>>(),
        })
    }
}

/// A plan factory paired with its schema. One map entry per plan, so a
/// factory can never exist without a (possibly empty) `PlanMeta` — the
/// `plans_allowed` shape is always derivable, never a separate lookup that
/// can fall out of sync.
#[derive(Clone)]
struct RegisteredPlan {
    factory: PlanFactory,
    meta: PlanMeta,
}

/// Registered devices, indexed by string name. The same physical device
/// usually appears under more than one trait — register each role explicitly.
///
/// `Clone` is implemented (cheap — every value is an `Arc<dyn ...>`)
/// so callers can share the registry between the `Server` and a
/// daemon-side evaluator that publishes the same devices into a Lua
/// state.
#[derive(Clone, Default)]
pub struct Registry {
    plans: HashMap<String, RegisteredPlan>,
    readables: HashMap<String, Arc<dyn ReadableObj>>,
    movables: HashMap<String, Arc<dyn MovableObj>>,
    locatables: HashMap<String, Arc<dyn LocatableObj>>,
    triggerables: HashMap<String, Arc<dyn TriggerableObj>>,
    stageables: HashMap<String, Arc<dyn StageableObj>>,
    flyables: HashMap<String, Arc<dyn FlyableObj>>,
    collectables: HashMap<String, Arc<dyn CollectableObj>>,
    /// Devices with `#[lua_methods]`-derived `LuaExposable` impls.
    /// Surfaced through the daemon's Lua state as device-specific
    /// methods on the device global. See `host/manager_lua.rs`.
    lua_exposed: HashMap<String, LuaExposedEntry>,
}

impl Registry {
    /// Build empty.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a plan factory with no schema — `plans_allowed` reports it
    /// with an empty parameter list and description. Prefer
    /// [`Registry::register_plan_with_meta`] so clients receive real
    /// parameter types/defaults.
    pub fn register_plan(&mut self, name: impl Into<String>, factory: PlanFactory) {
        self.plans.insert(
            name.into(),
            RegisteredPlan {
                factory,
                meta: PlanMeta::default(),
            },
        );
    }

    /// Register a plan factory together with its schema ([`PlanMeta`]),
    /// surfaced verbatim by `plans_allowed` / `plans_existing`.
    pub fn register_plan_with_meta(
        &mut self,
        name: impl Into<String>,
        factory: PlanFactory,
        meta: PlanMeta,
    ) {
        self.plans
            .insert(name.into(), RegisteredPlan { factory, meta });
    }

    /// Register a `ReadableObj` device under a name.
    pub fn register_readable(&mut self, name: impl Into<String>, obj: Arc<dyn ReadableObj>) {
        self.readables.insert(name.into(), obj);
    }

    /// Register a `MovableObj` device.
    pub fn register_movable(&mut self, name: impl Into<String>, obj: Arc<dyn MovableObj>) {
        self.movables.insert(name.into(), obj);
    }

    /// Register a `LocatableObj` device. Locatable extends Movable;
    /// register both for full motor surface (set + locate).
    pub fn register_locatable(&mut self, name: impl Into<String>, obj: Arc<dyn LocatableObj>) {
        self.locatables.insert(name.into(), obj);
    }

    /// Register a `TriggerableObj` device.
    pub fn register_triggerable(&mut self, name: impl Into<String>, obj: Arc<dyn TriggerableObj>) {
        self.triggerables.insert(name.into(), obj);
    }

    /// Register a `StageableObj` device.
    pub fn register_stageable(&mut self, name: impl Into<String>, obj: Arc<dyn StageableObj>) {
        self.stageables.insert(name.into(), obj);
    }

    /// Register a `FlyableObj` device.
    pub fn register_flyable(&mut self, name: impl Into<String>, obj: Arc<dyn FlyableObj>) {
        self.flyables.insert(name.into(), obj);
    }

    /// Register a `CollectableObj` device.
    pub fn register_collectable(&mut self, name: impl Into<String>, obj: Arc<dyn CollectableObj>) {
        self.collectables.insert(name.into(), obj);
    }

    /// Register the device's `#[lua_methods]` table for daemon-Lua
    /// exposure. Devices that implement `crate::core::LuaExposable`
    /// (auto-generated by `#[lua_methods]`) call this once after
    /// registering their roles, passing their `Arc<Self>` and
    /// `Self::lua_methods()`.
    pub fn register_lua_methods<T: crate::core::LuaExposable + 'static>(
        &mut self,
        name: impl Into<String>,
        device: Arc<T>,
    ) {
        let any: Arc<dyn Any + Send + Sync> = device;
        self.lua_exposed.insert(
            name.into(),
            LuaExposedEntry {
                methods: T::lua_methods(),
                device: any,
            },
        );
    }

    /// Look up a device's lua-exposed entry by name (used by the
    /// daemon-side Lua bridge in `host/manager_lua.rs`).
    pub fn lua_exposed(&self, name: &str) -> Option<&LuaExposedEntry> {
        self.lua_exposed.get(name)
    }

    /// Look up a `ReadableObj` by name.
    pub fn readable(&self, name: &str) -> Option<&Arc<dyn ReadableObj>> {
        self.readables.get(name)
    }

    /// Look up a `MovableObj` by name.
    pub fn movable(&self, name: &str) -> Option<&Arc<dyn MovableObj>> {
        self.movables.get(name)
    }

    /// Look up a `LocatableObj` by name.
    pub fn locatable(&self, name: &str) -> Option<&Arc<dyn LocatableObj>> {
        self.locatables.get(name)
    }

    /// Look up a `TriggerableObj` by name.
    pub fn triggerable(&self, name: &str) -> Option<&Arc<dyn TriggerableObj>> {
        self.triggerables.get(name)
    }

    /// Look up a `StageableObj` by name.
    pub fn stageable(&self, name: &str) -> Option<&Arc<dyn StageableObj>> {
        self.stageables.get(name)
    }

    /// Look up a `FlyableObj` by name.
    pub fn flyable(&self, name: &str) -> Option<&Arc<dyn FlyableObj>> {
        self.flyables.get(name)
    }

    /// Look up a `CollectableObj` by name.
    pub fn collectable(&self, name: &str) -> Option<&Arc<dyn CollectableObj>> {
        self.collectables.get(name)
    }

    /// Look up a registered plan factory by name.
    pub fn plan(&self, name: &str) -> Option<&PlanFactory> {
        self.plans.get(name).map(|r| &r.factory)
    }

    /// All plan names.
    pub fn plan_names(&self) -> Vec<String> {
        let mut v: Vec<_> = self.plans.keys().cloned().collect();
        v.sort();
        v
    }

    /// Plans as a rich dict `{name: {name, module, description, properties,
    /// parameters}}` matching bluesky-queueserver's `_process_plan` wire shape.
    /// Used by `plans_existing` (every registered plan).
    pub fn plan_dict(&self) -> serde_json::Value {
        self.plans_dict_subset(&self.plan_names())
    }

    /// Rich plan dict for a subset of names (e.g. a group-filtered
    /// `plans_allowed` list). Each value is the plan's `_process_plan`-shaped
    /// schema drawn from its [`PlanMeta`]; names not registered are skipped.
    pub fn plans_dict_subset(&self, names: &[String]) -> serde_json::Value {
        let mut map = serde_json::Map::new();
        for name in names {
            if let Some(r) = self.plans.get(name) {
                map.insert(name.clone(), r.meta.to_json(name));
            }
        }
        serde_json::Value::Object(map)
    }

    /// Devices as a rich dict `{name: {name, description, module}}`
    /// matching the bluesky `devices_allowed` / `devices_existing` wire shape.
    /// Every registered device (used by `devices_existing`).
    pub fn device_dict(&self) -> serde_json::Value {
        self.devices_dict_subset(&self.device_names())
    }

    /// Rich device dict for a subset of names (e.g. a group-filtered
    /// `devices_allowed` list). Names not registered are skipped.
    pub fn devices_dict_subset(&self, names: &[String]) -> serde_json::Value {
        let known: std::collections::BTreeSet<String> = self.device_names().into_iter().collect();
        let mut map = serde_json::Map::new();
        for name in names {
            if known.contains(name) {
                map.insert(
                    name.clone(),
                    serde_json::json!({
                        "name": name,
                        "description": "",
                        "module": "bsrs_qs",
                    }),
                );
            }
        }
        serde_json::Value::Object(map)
    }

    /// Look up `name` across every role table and return the first
    /// `NamedObj::inspect_dyn` result. The map is sorted-iterated in
    /// the same role order as registration so the result is stable.
    /// `None` if the name is not registered in any role.
    pub fn inspect_device(&self, name: &str) -> Option<serde_json::Value> {
        if let Some(o) = self.readables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.movables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.triggerables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.stageables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.flyables.get(name) {
            return Some(o.inspect_dyn());
        }
        if let Some(o) = self.collectables.get(name) {
            return Some(o.inspect_dyn());
        }
        None
    }

    /// All device names (union over all role registrations + lua-only
    /// devices). A device registered solely via
    /// `register_lua_methods` (no readable/movable/...) still appears
    /// here so the daemon Lua state publishes it as a global.
    pub fn device_names(&self) -> Vec<String> {
        let mut s = std::collections::BTreeSet::new();
        for k in self.readables.keys() {
            s.insert(k.clone());
        }
        for k in self.movables.keys() {
            s.insert(k.clone());
        }
        for k in self.locatables.keys() {
            s.insert(k.clone());
        }
        for k in self.triggerables.keys() {
            s.insert(k.clone());
        }
        for k in self.stageables.keys() {
            s.insert(k.clone());
        }
        for k in self.flyables.keys() {
            s.insert(k.clone());
        }
        for k in self.collectables.keys() {
            s.insert(k.clone());
        }
        for k in self.lua_exposed.keys() {
            s.insert(k.clone());
        }
        s.into_iter().collect()
    }

    /// Convenience: register the canonical `count` plan (`count(detectors, num)`).
    /// Args shape: `{"args": ["det1", "det2", ...], "kwargs": {"num": 5}}`
    /// or `{"args": [["det1", "det2"], 5]}`.
    pub fn register_plan_count(&mut self, name: impl Into<String>) {
        let factory: PlanFactory = Arc::new(|reg, args| {
            let (dets_raw, num) = parse_count_args(args)?;
            let mut dets: Vec<Arc<dyn ReadableObj>> = Vec::with_capacity(dets_raw.len());
            for d in &dets_raw {
                let obj = reg
                    .readable(d)
                    .ok_or_else(|| format!("unknown detector: {d}"))?
                    .clone();
                dets.push(obj);
            }
            Ok(crate::plans::count(dets, num))
        });
        let meta = PlanMeta {
            description: Some("Trigger and read a list of detectors `num` times.".to_string()),
            parameters: vec![
                ParamSpec::new("detectors", ParamKind::PositionalOrKeyword)
                    .with_type("typing.List[Readable]")
                    .with_description("Readable device names to trigger and read at each point."),
                // `num` is required in bsrs (the factory errors when absent),
                // so no default is advertised — a divergence from bluesky's
                // `num=1`, matching this factory's actual contract.
                ParamSpec::new("num", ParamKind::PositionalOrKeyword)
                    .with_type("int")
                    .with_description("Number of readings to take."),
            ],
        };
        self.register_plan_with_meta(name, factory, meta);
    }
}

fn parse_count_args(args: &Value) -> Result<(Vec<String>, usize), String> {
    // Accept both kwargs- and positional-style.
    if let Some(obj) = args.as_object() {
        let detectors = obj
            .get("args")
            .and_then(|a| a.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|v| v.as_str().map(|s| s.to_string()))
                    .collect::<Vec<_>>()
            })
            .or_else(|| {
                obj.get("kwargs")
                    .and_then(|k| k.get("detectors"))
                    .and_then(|d| d.as_array())
                    .map(|a| {
                        a.iter()
                            .filter_map(|v| v.as_str().map(|s| s.to_string()))
                            .collect::<Vec<_>>()
                    })
            })
            .unwrap_or_default();
        let num = obj
            .get("kwargs")
            .and_then(|k| k.get("num"))
            .and_then(|n| n.as_u64())
            .or_else(|| {
                obj.get("args")
                    .and_then(|a| a.as_array())
                    .and_then(|a| a.last())
                    .and_then(|v| v.as_u64())
            })
            .ok_or_else(|| "count: missing 'num' argument".to_string())? as usize;
        Ok((detectors, num))
    } else {
        Err(format!("count args must be object; got {args}"))
    }
}
